import os
import sqlite3
from pathlib import Path

import psycopg
from psycopg.rows import dict_row


# ============================================================
# DATABASE CONFIGURATION
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
DATABASE_PATH = DATA_DIR / "rocket_guardian.db"


def using_postgres():
    return bool(os.getenv("SUPABASE_DB_URL"))


# ============================================================
# POSTGRES COMPATIBILITY LAYER
# ============================================================

class PostgresCursor:
    """Compatibility wrapper for the existing ? placeholders."""

    def __init__(self, cursor):
        self._cursor = cursor

    def execute(self, query, params=None):
        query = query.replace("?", "%s")
        if params is None:
            self._cursor.execute(query)
        else:
            self._cursor.execute(query, params)
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def close(self):
        self._cursor.close()


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def cursor(self):
        return PostgresCursor(
            self._connection.cursor(row_factory=dict_row)
        )

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


# ============================================================
# DATABASE CONNECTION
# ============================================================

def get_connection():
    """
    Use Supabase PostgreSQL when SUPABASE_DB_URL is set.
    Otherwise use local SQLite.
    """

    postgres_url = os.getenv("SUPABASE_DB_URL")

    if postgres_url:
        return PostgresConnection(
            psycopg.connect(postgres_url)
        )

    DATA_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    connection = sqlite3.connect(
        DATABASE_PATH
    )

    connection.row_factory = sqlite3.Row

    return connection


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

def initialize_database():
    connection = get_connection()

    try:
        cursor = connection.cursor()

        if using_postgres():
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS customers (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS missions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id BIGINT NOT NULL
                        REFERENCES customers(id)
                        ON DELETE CASCADE,
                    name TEXT NOT NULL,
                    description TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS telemetry_runs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    mission_id BIGINT NOT NULL
                        REFERENCES missions(id)
                        ON DELETE CASCADE,
                    source_filename TEXT,
                    sample_count INTEGER,
                    ai_detection_count INTEGER,
                    overall_risk DOUBLE PRECISION,
                    risk_level TEXT,
                    primary_risk_sensor TEXT,
                    peak_time_s DOUBLE PRECISION,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_missions_customer_id
                ON missions(customer_id)
                """
            )

            cursor.execute(
                """
                CREATE INDEX IF NOT EXISTS idx_telemetry_runs_mission_id
                ON telemetry_runs(mission_id)
                """
            )

        else:
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS customers (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS missions (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    customer_id INTEGER,
                    name TEXT NOT NULL,
                    description TEXT,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (customer_id) REFERENCES customers(id)
                )
                """
            )

            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS telemetry_runs (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    mission_id INTEGER,
                    source_filename TEXT,
                    sample_count INTEGER,
                    ai_detection_count INTEGER,
                    overall_risk REAL,
                    risk_level TEXT,
                    primary_risk_sensor TEXT,
                    peak_time_s REAL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (mission_id) REFERENCES missions(id)
                )
                """
            )

        connection.commit()

    finally:
        connection.close()


# ============================================================
# CREATE CUSTOMER
# ============================================================

def create_customer(name, email):
    connection = get_connection()

    try:
        cursor = connection.cursor()

        if using_postgres():
            cursor.execute(
                """
                INSERT INTO customers (name, email)
                VALUES (?, ?)
                RETURNING id
                """,
                (name, email),
            )
            row = cursor.fetchone()
            connection.commit()
            return int(row["id"])

        cursor.execute(
            """
            INSERT INTO customers (name, email)
            VALUES (?, ?)
            """,
            (name, email),
        )
        connection.commit()
        return int(cursor.lastrowid)

    finally:
        connection.close()


# ============================================================
# CREATE MISSION
# ============================================================

def create_mission(customer_id, name, description=None):
    connection = get_connection()

    try:
        cursor = connection.cursor()

        if using_postgres():
            cursor.execute(
                """
                INSERT INTO missions (
                    customer_id,
                    name,
                    description
                )
                VALUES (?, ?, ?)
                RETURNING id
                """,
                (customer_id, name, description),
            )
            row = cursor.fetchone()
            connection.commit()
            return int(row["id"])

        cursor.execute(
            """
            INSERT INTO missions (
                customer_id,
                name,
                description
            )
            VALUES (?, ?, ?)
            """,
            (customer_id, name, description),
        )
        connection.commit()
        return int(cursor.lastrowid)

    finally:
        connection.close()


# ============================================================
# SAVE TELEMETRY RUN
# ============================================================

def save_telemetry_run(
    mission_id,
    source_filename,
    sample_count,
    ai_detection_count,
    overall_risk,
    risk_level,
    primary_risk_sensor,
    peak_time_s,
):
    connection = get_connection()

    try:
        cursor = connection.cursor()

        if using_postgres():
            cursor.execute(
                """
                INSERT INTO telemetry_runs (
                    mission_id,
                    source_filename,
                    sample_count,
                    ai_detection_count,
                    overall_risk,
                    risk_level,
                    primary_risk_sensor,
                    peak_time_s
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                (
                    mission_id,
                    source_filename,
                    sample_count,
                    ai_detection_count,
                    overall_risk,
                    risk_level,
                    primary_risk_sensor,
                    peak_time_s,
                ),
            )
            row = cursor.fetchone()
            connection.commit()
            return int(row["id"])

        cursor.execute(
            """
            INSERT INTO telemetry_runs (
                mission_id,
                source_filename,
                sample_count,
                ai_detection_count,
                overall_risk,
                risk_level,
                primary_risk_sensor,
                peak_time_s
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                mission_id,
                source_filename,
                sample_count,
                ai_detection_count,
                overall_risk,
                risk_level,
                primary_risk_sensor,
                peak_time_s,
            ),
        )
        connection.commit()
        return int(cursor.lastrowid)

    finally:
        connection.close()


# ============================================================
# LIST CUSTOMERS
# ============================================================

def list_customers():
    connection = get_connection()

    try:
        cursor = connection.cursor()
        cursor.execute(
            """
            SELECT id, name, email, created_at
            FROM customers
            ORDER BY created_at DESC
            """
        )
        return cursor.fetchall()

    finally:
        connection.close()


# ============================================================
# LIST MISSIONS
# ============================================================

def list_missions(customer_id=None):
    connection = get_connection()

    try:
        cursor = connection.cursor()

        if customer_id is None:
            cursor.execute(
                """
                SELECT
                    id,
                    customer_id,
                    name,
                    description,
                    created_at
                FROM missions
                ORDER BY created_at DESC
                """
            )
        else:
            cursor.execute(
                """
                SELECT
                    id,
                    customer_id,
                    name,
                    description,
                    created_at
                FROM missions
                WHERE customer_id = ?
                ORDER BY created_at DESC
                """,
                (customer_id,),
            )

        return cursor.fetchall()

    finally:
        connection.close()


# ============================================================
# LIST TELEMETRY RUNS
# ============================================================

def list_telemetry_runs(mission_id=None):
    connection = get_connection()

    try:
        cursor = connection.cursor()

        if mission_id is None:
            cursor.execute(
                """
                SELECT
                    id,
                    mission_id,
                    source_filename,
                    sample_count,
                    ai_detection_count,
                    overall_risk,
                    risk_level,
                    primary_risk_sensor,
                    peak_time_s,
                    created_at
                FROM telemetry_runs
                ORDER BY created_at DESC
                """
            )
        else:
            cursor.execute(
                """
                SELECT
                    id,
                    mission_id,
                    source_filename,
                    sample_count,
                    ai_detection_count,
                    overall_risk,
                    risk_level,
                    primary_risk_sensor,
                    peak_time_s,
                    created_at
                FROM telemetry_runs
                WHERE mission_id = ?
                ORDER BY created_at DESC
                """,
                (mission_id,),
            )

        return cursor.fetchall()

    finally:
        connection.close()


# ============================================================
# FIND OR CREATE CUSTOMER
# ============================================================

def get_or_create_customer(name, email):
    name = str(name).strip()
    email = str(email).strip().lower()

    connection = get_connection()

    try:
        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT id
            FROM customers
            WHERE email = ?
            """,
            (email,),
        )

        row = cursor.fetchone()

        if row is not None:
            return int(row["id"])

        if using_postgres():
            cursor.execute(
                """
                INSERT INTO customers (name, email)
                VALUES (?, ?)
                RETURNING id
                """,
                (name, email),
            )
            row = cursor.fetchone()
            connection.commit()
            return int(row["id"])

        cursor.execute(
            """
            INSERT INTO customers (name, email)
            VALUES (?, ?)
            """,
            (name, email),
        )
        connection.commit()
        return int(cursor.lastrowid)

    finally:
        connection.close()


# ============================================================
# FIND TELEMETRY RUN
# ============================================================

def find_telemetry_run(
    source_filename,
    customer_id,
    mission_name,
):
    connection = get_connection()

    try:
        cursor = connection.cursor()

        cursor.execute(
            """
            SELECT
                tr.id
            FROM telemetry_runs tr
            JOIN missions m
                ON tr.mission_id = m.id
            WHERE tr.source_filename = ?
            AND m.customer_id = ?
            AND m.name = ?
            ORDER BY tr.id DESC
            LIMIT 1
            """,
            (
                source_filename,
                customer_id,
                mission_name,
            ),
        )

        return cursor.fetchone()

    finally:
        connection.close()


# ============================================================
# INITIALIZE DATABASE
# ============================================================

initialize_database()
